spring.application.name=backend
spring.datasource.url=${MYSQLURL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=${PORT:5000}
jwt.secret=${JWT_SECRET:sfjsgjhfdsgfyue65768762yiuwyei7ewqeyueqy5785qw7e6q}